### ISSUE TITLE
raspberry pi - raspbian error cc failed with exit status 1

### ISSUE THREAD

**Issue by uiisse** [viblo/pymunk#101]
this is my log

pi@raspberrypi:~ $ sudo pip install pymunk
Downloading/unpacking pymunk
  Downloading pymunk-5.0.0.zip (4.0MB): 4.0MB downloaded
  Running setup.py (path:/tmp/pip-build-S0Av7A/pymunk/setup.py) egg_info for package pymunk
    
    no previously-included directories found matching 'examples/.ipynb_checkpoints'
Downloading/unpacking cffi (from pymunk)
  Downloading cffi-1.7.0.tar.gz (400kB): 400kB downloaded
  Running setup.py (path:/tmp/pip-build-S0Av7A/cffi/setup.py) egg_info for package cffi
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    
Downloading/unpacking pycparser (from cffi->pymunk)
  Downloading pycparser-2.14.tar.gz (223kB): 223kB downloaded
  Running setup.py (path:/tmp/pip-build-S0Av7A/pycparser/setup.py) egg_info for package pycparser
    
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
Installing collected packages: pymunk, cffi, pycparser
  Running setup.py install for pymunk
    
    no previously-included directories found matching 'examples/.ipynb_checkpoints'
    cc -std=gnu99 -ffast-math -DCHIPMUNK_FFI -g -DCP_USE_CGPOINTS=0 -DNDEBUG -m32 -fPIC -O3 -Ichipmunk_src/include -c chipmunk_src/src/cpMarch.c -o chipmunk_src/src/cpMarch.o
    cc: error: unrecognized command line option ‘-m32’
    error: command 'cc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-S0Av7A/pymunk/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-o3adz7-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-armv7l-2.7

creating build/lib.linux-armv7l-2.7/pymunk

copying pymunk/transform.py -> build/lib.linux-armv7l-2.7/pymunk

copying pymunk/collision_handler.py -> build/lib.linux-armv7l-2.7/pymunk

copying pymunk/shape_filter.py -> build/lib.linux-armv7l-2.7/pymunk

copying pymunk/contact_point_set.py -> build/lib.linux-armv7l-2.7/pymunk

copying pymunk/space_debug_draw_options.py -> build/lib.linux-armv7l-2.7/pymunk

copying pymunk/query_info.py -> build/lib.linux-armv7l-2.7/pymunk

copying pymunk/_chipmunk_cffi_abi.py -> build/lib.linux-armv7l-2.7/pymunk

copying pymunk/bb.py -> build/lib.linux-armv7l-2.7/pymunk

copying pymunk/constraint.py -> build/lib.linux-armv7l-2.7/pymunk

copying pymunk/util.py -> build/lib.linux-armv7l-2.7/pymunk

copying pymunk/matplotlib_util.py -> build/lib.linux-armv7l-2.7/pymunk

copying pymunk/arbiter.py -> build/lib.linux-armv7l-2.7/pymunk

copying pymunk/body.py -> build/lib.linux-armv7l-2.7/pymunk

copying pymunk/shapes.py -> build/lib.linux-armv7l-2.7/pymunk

copying pymunk/autogeometry.py -> build/lib.linux-armv7l-2.7/pymunk

copying pymunk/pygame_util.py -> build/lib.linux-armv7l-2.7/pymunk

copying pymunk/vec2d.py -> build/lib.linux-armv7l-2.7/pymunk

copying pymunk/space.py -> build/lib.linux-armv7l-2.7/pymunk

copying pymunk/_libload.py -> build/lib.linux-armv7l-2.7/pymunk

copying pymunk/pyglet_util.py -> build/lib.linux-armv7l-2.7/pymunk

copying pymunk/__init__.py -> build/lib.linux-armv7l-2.7/pymunk

copying pymunk/_chipmunk_cffi.py -> build/lib.linux-armv7l-2.7/pymunk

creating build/lib.linux-armv7l-2.7/pymunkoptions

copying pymunkoptions/__init__.py -> build/lib.linux-armv7l-2.7/pymunkoptions

running egg_info

writing requirements to pymunk.egg-info/requires.txt

writing pymunk.egg-info/PKG-INFO

writing top-level names to pymunk.egg-info/top_level.txt

writing dependency_links to pymunk.egg-info/dependency_links.txt

warning: manifest_maker: standard file '-c' not found

reading manifest file 'pymunk.egg-info/SOURCES.txt'

reading manifest template 'MANIFEST.in'

no previously-included directories found matching 'examples/.ipynb_checkpoints'

writing manifest file 'pymunk.egg-info/SOURCES.txt'

running build_ext

cc -std=gnu99 -ffast-math -DCHIPMUNK_FFI -g -DCP_USE_CGPOINTS=0 -DNDEBUG -m32 -fPIC -O3 -Ichipmunk_src/include -c chipmunk_src/src/cpMarch.c -o chipmunk_src/src/cpMarch.o

cc: error: unrecognized command line option ‘-m32’

error: command 'cc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-S0Av7A/pymunk/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-o3adz7-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-S0Av7A/pymunk
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 48: ordinal not in range(128)

**Comment by uiisse** [comment]
on RASPBERRY PI 
solved with

sudo apt-get install python-dev (optional) 
sudo apt-get install libffi-dev

and finally

sudo pip install pymunk
