### ISSUE TITLE
Cannot locate Chipmunk Library

### ISSUE THREAD

**Issue by KevinShengZK** [viblo/pymunk#201]
My current OS: macOS BigSur
So using python (version 3.9), arcade (version 2.4.3) pymunk (version 5.7.0)  cannot locate libchipmunk.dylib which is already there.
Pymunk reported the error as 'you don't have a compiled version of Chipmunk' while chipmunk is already installed (verision 1.0.1).

My arcade is installed by pip automatically, but to solve 'pymunkoptions' error i uninstalled pymunk and installed it again in version 5.7.0

### When scripts including arcade run, error report as follows:
```
/Users/kevinsheng/PycharmProjects/pythonProject3/venv/bin/python /Users/kevinsheng/PycharmProjects/pythonProject3/main.py
Traceback (most recent call last):
  File "/Users/kevinsheng/PycharmProjects/pythonProject3/main.py", line 5, in <module>
    import arcade
  File "/Users/kevinsheng/PycharmProjects/pythonProject3/venv/lib/python3.9/site-packages/arcade/__init__.py", line 103, in <module>
    from .drawing_support import calculate_hit_box_points_detailed
  File "/Users/kevinsheng/PycharmProjects/pythonProject3/venv/lib/python3.9/site-packages/arcade/drawing_support.py", line 9, in <module>
    import pymunk
  File "/Users/kevinsheng/PycharmProjects/pythonProject3/venv/lib/python3.9/site-packages/pymunk/__init__.py", line 75, in <module>
    from . import _chipmunk_cffi
  File "/Users/kevinsheng/PycharmProjects/pythonProject3/venv/lib/python3.9/site-packages/pymunk/_chipmunk_cffi.py", line 3, in <module>
    from pymunk._chipmunk_cffi_abi import ffi, lib, lib_path 
  File "/Users/kevinsheng/PycharmProjects/pythonProject3/venv/lib/python3.9/site-packages/pymunk/_chipmunk_cffi_abi.py", line 1475, in <module>
    lib, lib_path = load_library(ffi, "chipmunk", debug_lib=_lib_debug)
  File "/Users/kevinsheng/PycharmProjects/pythonProject3/venv/lib/python3.9/site-packages/pymunk/_libload.py", line 61, in load_library
    lib = ffi.dlopen(lib_path)
  File "/Users/kevinsheng/PycharmProjects/pythonProject3/venv/lib/python3.9/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/Users/kevinsheng/PycharmProjects/pythonProject3/venv/lib/python3.9/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/Users/kevinsheng/PycharmProjects/pythonProject3/venv/lib/python3.9/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library '/Users/kevinsheng/PycharmProjects/pythonProject3/venv/lib/python3.9/site-packages/pymunk/libchipmunk.dylib': dlopen(/Users/kevinsheng/PycharmProjects/pythonProject3/venv/lib/python3.9/site-packages/pymunk/libchipmunk.dylib, 2): no suitable image found.  Did find:
	/Users/kevinsheng/PycharmProjects/pythonProject3/venv/lib/python3.9/site-packages/pymunk/libchipmunk.dylib: no matching architecture in universal wrapper
	/Users/kevinsheng/PycharmProjects/pythonProject3/venv/lib/python3.9/site-packages/pymunk/libchipmunk.dylib: no matching architecture in universal wrapper.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/Users/kevinsheng/PycharmProjects/pythonProject3/venv/lib/python3.9/site-packages/pymunk/libchipmunk.dylib'

Failed to load Pymunk library.

This error usually means that you don't have a compiled version of Chipmunk in
the correct spot where Pymunk can find it. If you tried to run Pymunk without
installing it properly this can be the result.

The good news is that it is usually enough (at least on *nix and OS X) to
run the build command:

You compile Chipmunk with
> python setup.py build_ext --inplace
and then verify with
> python -m pymunk.test

(for complete instructions please see the readme file)

Another cause of this problem could be if you didnt included the Chipmunk
library when using a freeze tool such as Py2exe or PyInstaller. Please see the
examples for how to include the library file when freezing a binary.

If it still doesnt work, please report as a bug on the issue tracker at
https://github.com/viblo/pymunk/issues
Remember to include information about your OS, which version of python you use
and the version of pymunk you tried to run. A description of what you did to
trigger the error is also good. Please include the exception traceback if any
(usually found below this message).


Process finished with exit code 1
```

### chipmunklib.dylib file opens in terminal as follows:
```
kevinsheng@192 ~ % file /Users/kevinsheng/PycharmProjects/pythonProject3/venv/lib/python3.9/site-packages/pymunk/libchipmunk.dylib
/Users/kevinsheng/PycharmProjects/pythonProject3/venv/lib/python3.9/site-packages/pymunk/libchipmunk.dylib: Mach-O universal binary with 2 architectures: [i386:Mach-O dynamically linked shared library i386] [x86_64:Mach-O 64-bit dynamically linked shared library x86_64]
/Users/kevinsheng/PycharmProjects/pythonProject3/venv/lib/python3.9/site-packages/pymunk/libchipmunk.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
/Users/kevinsheng/PycharmProjects/pythonProject3/venv/lib/python3.9/site-packages/pymunk/libchipmunk.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
```

Best hopes for there is a solution to this.

**Comment by viblo** [comment]
Do you happen to run on the M1 / ARM mac? Or do you have the intel one?

**Comment by viblo** [comment]
Another question: Is it possible for you to update to a newer version of arcade and pymunk? The packaging of the chipmunk library changed quite a bit in pymunk 6, and I think its now more robust against these kinds of problems.

**Comment by KevinShengZK** [comment]
My Mac is Apple M1, and installing pymunk 6 creates 'no pymunkoptions' issue

**Comment by viblo** [comment]
Ok, then you need to upgrade to a Pymunk 6.x. Pymunk 5.7 was released M1, and does not support it (It probably could be made to work, but that will require modifications to its setup.py file). 

I think your best way forward is to upgrade Pymunk. Since you use it with arcade, you will have to update arcade first, otherwise you will get the pymunkoptions error.
