### ISSUE TITLE
Legacy pymunk on arm devices

### ISSUE THREAD

**Issue by mcpalmer1980** [viblo/pymunk#204]
Pymunk has unfortunately broken compatibility with projects made for version 4 and 5. In order to keep those old projects working on modern arm devices I recommend updating the setup.py for 4.0 and 5.7 to compile for arm64 devices. I am getting an error compiling them on the chroot provided by the 351elec community for retro portable consoles. After a little experimenting I have failed to make it work.

```
root@rk3326-dev:/pymunk-5.7.0# python3 setup.py build_ext --inplace
running build_ext
cc -std=gnu99 -ffast-math -DCHIPMUNK_FFI -g -DCP_USE_CGPOINTS=0 -DNDEBUG -fPIC -O3 -m64 -Ichipmunk_src/include -c chipmunk_src/src/cpSpaceComponent.c -o chipmunk_src/src/cpSpaceComponent.o
cc: error: unrecognized command line option ‘-m64’
error: command 'cc' failed with exit status 1
root@rk3326-dev:/pymunk-5.7.0# 
```

**Comment by mcpalmer1980** [comment]
After changing setup.py to use march=armv8-a it compiled libchipmunk.so. After that I can import pymunk in my cross-compiling chroot. But when I try to import pymunk from the pyinstaller frozen binary on my arm device, I get an error.
```
Traceback (most recent call last):
  File "run_game.py", line 19, in <module>
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/storage/roms/ports/pygame/hoverball/run_game.py", line 12, in <module>
    import main
  File "/storage/roms/ports/pygame/hoverball/lib/main.py", line 6, in <module>
    from constants import *
  File "/storage/roms/ports/pygame/hoverball/lib/constants.py", line 15, in <module>
    import pymunk
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "pymunk/__init__.py", line 67, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "pymunk/_chipmunk_cffi.py", line 5, in <module>
ModuleNotFoundError: No module named 'pymunk._chipmunk'
[5638] Failed to execute script 'run_game' due to unhandled exception!
```
I tried to port my game hoverball to the latest pymunk instead of building version 5.7.0. I fixed the Vec2d() initializers, and added the missing body objects to space before adding the shape. But I CANNOT get passed the immutable Vec2ds!!!!

**Comment by viblo** [comment]
From the error it looks like either the .so file is not in the correct place. Did you include it with PyInstaller? For 5.7 there's special logic around loading of the library file here: https://github.com/viblo/pymunk/blob/pymunk-5.7.0/pymunk/_libload.py

**Comment by viblo** [comment]
Closing since reporter didnt reply in a long time.
