### ISSUE TITLE
Getting: MemoryError: Cannot allocate write+execute memory for ffi.callback()

### ISSUE THREAD

**Issue by danaki** [viblo/pymunk#217]
I'm running OSX, Apple M1. Getting this exception:
```
(gs) {15:58}~/work/Python-Galton-Board-:master ✓ ➭ python main.py
pygame 2.1.2 (SDL 2.0.18, Python 3.10.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/Users/jurijs.pimenovs/work/Python-Galton-Board-/main.py", line 12, in <module>
    draw_options = pymunk.pygame_util.DrawOptions(surface)
  File "/opt/homebrew/anaconda3/envs/gs/lib/python3.10/site-packages/pymunk/pygame_util.py", line 124, in __init__
    super(DrawOptions, self).__init__()
  File "/opt/homebrew/anaconda3/envs/gs/lib/python3.10/site-packages/pymunk/space_debug_draw_options.py", line 89, in __init__
    def f1(pos, angle, radius, outline_color, fill_color, _):  # type: ignore
MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks
```

**Comment by viblo** [comment]
Thanks for the report! 
Interesting error, I will have to investigate a bit.. Seems like callback handling needs to be updated..

**Comment by viblo** [comment]
Fix will be included in the next Pymunk version.

**Comment by viblo** [comment]
Pymunk 6.3 released. Includes the fix for this issue.
