### ISSUE TITLE
KeyError: using_sprites_pyglet: 'pymunk_logo_googlecode.png'

### ISSUE THREAD

**Issue by MichaelQuaMan** [viblo/pymunk#222]
**Summary**
- Running `$ python -m pymunk.examples.using_sprites_pyglet`
- Got a `KeyError` looking for image file
- Expectation would be for it to `just work` as the others do

**Primary Exception**
```
KeyError: 'pymunk_logo_googlecode.png'
```

**Secondary Exception**
```
pyglet.resource.ResourceNotFoundException: Resource 'pymunk_logo_googlecode.png' was not found on the path.  Ensure that the filename has the correct capitalisation.
```
**Details**
```
$ python -m pymunk.examples.using_sprites_pyglet
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\sandbox\lib\site-packages\pyglet\resource.py", line 506, in file
    location = self._index[name]
KeyError: 'pymunk_logo_googlecode.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\sandbox\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\sandbox\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\sandbox\lib\site-packages\pymunk\examples\using_sprites_pyglet.py", line 21, in <module>
    logo_img = pyglet.resource.image("pymunk_logo_googlecode.png")
  File "C:\ProgramData\Anaconda3\envs\sandbox\lib\site-packages\pyglet\resource.py", line 628, in image
    identity = self._cached_images[name] = self._alloc_image(name, atlas, border)
  File "C:\ProgramData\Anaconda3\envs\sandbox\lib\site-packages\pyglet\resource.py", line 553, in _alloc_image
    file = self.file(name)
  File "C:\ProgramData\Anaconda3\envs\sandbox\lib\site-packages\pyglet\resource.py", line 509, in file
    raise ResourceNotFoundException(name)
```

**Comment by MichaelQuaMan** [comment]
Interesting, looks like the `pymunk_logo_googlecode.png` is in the examples folder. I'll see if I can figure out why it's not finding it.

**Comment by viblo** [comment]
This is a bug. If pymunk is installed in develop/edit mode (e.g. with `pip install -e`) then it works, and I never tried these examples from a pypi installation. I will fix.

**Comment by viblo** [comment]
The fix is now in master and will be included in the next release of Pymunk.
