### ISSUE TITLE
raspberrypi raspbian - cannot build chipmunk

### ISSUE THREAD

**Issue by marwie** [viblo/pymunk#82]
I'm trying to get pymunk up and running on my raspberrypi but I can't get the chipmunk library to work. I tried to follow the instructions and also tried to download chipmunk + build/install it, which didn't work either.

I built chipmunk with cmake . inside chipmunk_src: 
```
pi@raspberrypi ~/pymunk-4.0.0/chipmunk_src $ cmake .
...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/pymunk-4.0.0/chipmunk_src
```
the command make didn't change anything obvious:
```
pi@raspberrypi ~/pymunk-4.0.0/chipmunk_src $ make
pi@raspberrypi ~/pymunk-4.0.0/chipmunk_src $ cd ../
pi@raspberrypi ~/pymunk-4.0.0 $ python
>>> import pymunk
Loading chipmunk for Linux (32bit) [/home/pi/pymunk-4.0.0/pymunk/libchipmunk.so]
Failed to load pymunk library.
....
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pymunk/__init__.py", line 58, in <module>
    from . import _chipmunk as cp
  File "pymunk/_chipmunk.py", line 13, in <module>
    chipmunk_lib = load_library("chipmunk", debug_lib=_lib_debug)
  File "pymunk/libload.py", line 68, in load_library
    lib = platform_specific_functions()['library_loader'].LoadLibrary(libfn)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/pi/pymunk-4.0.0/pymunk/libchipmunk.so: cannot open shared object file: No such file or directory
```
What i don't understand is that this file exists: /home/pi/pymunk-4.0.0/pymunk/libchipmunk.so

When trying to build chipmunk i get the following error:
```
pi@raspberrypi ~/pymunk-4.0.0 $ python setup.py build_chipmunk
running build_chipmunk
compiling chipmunk in Debug mode (Defualt, prints debug output and asserts)
cc -std=gnu99 -ffast-math -DCHIPMUNK_FFI -Wno-unknown-pragmas -fPIC -DCP_USE_CGPOINTS=0 -m32 -O3 -Ichipmunk_src/include/chipmunk -c chipmunk_src/._cpSpatialIndex.c -o chipmunk_src/._cpSpatialIndex.o
cc1: error: unrecognized command line option '-m32'
error: command 'cc' failed with exit status 1
```

I hope someone has a solution to this. Uncommenting the m32 lines inside the CMakeLists.txt didn't help (it just threw more errors at me)

Thank you in advance!

**Comment by viblo** [comment]
Since the compile method has changed a lot in the new pymunk 5.0 just released Ill close this issue. If there are still problems feel free to open a new issue.
